"""Relaunch jobs whose route searched for the wrong stationary point.

The correctness rule that shapes this whole module: a transition state that was
launched with a plain ``Opt`` walked downhill and converged to a *minimum*. That
converged geometry, and every checkpoint written from it, is not a transition
state guess -- it is the wrong answer. So unlike ``restart.py``, which resumes
an interrupted ladder from its own checkpoint, a route relaunch always rebuilds
from the **original input geometry** and writes to **fresh checkpoint names**,
leaving the poisoned outputs and checkpoints archived and untouched beside it.

That rule decides how spin ladders are handled. A ladder input generated by
``prepare-spins`` carries its coordinates, so it is corrected stage by stage and
its one-spin-flip-at-a-time chain is preserved exactly: every ``%chk``/``%oldchk``
is renamed the same way, so stage k still reads stage k-1. A *restart* input from
``prepare-spin-restarts`` is different -- it has no coordinates at all, only
``%oldchk`` plus ``Geom=Checkpoint`` pointing at a seed copied out of the
interrupted run. Correcting that in place would both reference a checkpoint this
tool renamed out from under it and continue from the collapsed geometry, so
instead the whole restart lineage is retired and the **root** ladder is rebuilt
from its real coordinates, restoring the complete high-to-low pathway.

Everything happens in place, in the campaign's existing batch folders, so the
saved Slurm batch map stays valid and the campaign is resubmitted with the same
head launcher. Nothing is ever deleted. ``_preflight`` refuses any plan that
would leave the ``inputs.txt``-driven launchers inconsistent, and ``_verify``
reads the result back afterwards.
"""
from __future__ import annotations

import csv
import hashlib
import json
import os
import re
import shutil
from dataclasses import dataclass, field
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

from .route_audit import audit_campaign_routes, find_manifest, read_manifest
from .routes import (
    corrected_minimum_route,
    corrected_saddle_route,
    geometry_source,
    route_optimizes,
    stage_route,
)

_LINK1_SPLIT_RE = re.compile(r"(^\s*--\s*link1\s*--\s*$)", re.IGNORECASE | re.MULTILINE)
_CHK_RE = re.compile(r"^(\s*%(?:old)?chk\s*=\s*)(\S+)\s*$", re.IGNORECASE | re.MULTILINE)
_MARKER_SUFFIXES = (".status", ".rc", ".started", ".finished")

RELAUNCH_COLUMNS = [
    "submission_active", "relaunch_attempt", "relaunch_reason", "relaunch_root_input",
    "relaunch_of_job_id", "relaunch_source_output", "relaunch_route_before",
    "relaunch_route_after",
    # Stamped on the *superseded* rows so the archived log is permanently
    # self-describing: `collect` refuses those labels on this column alone,
    # without having to re-derive the verdict from files that may move.
    "route_invalidated", "superseded_by_job_id",
]

PLAN_COLUMNS = [
    "attempt", "batch", "original_input", "new_input", "config_type", "findings",
    "previous_state", "geometry_source", "rebuilt_from", "retired_inputs",
    "ladder_stages", "archived_output", "new_output", "route_before", "route_after",
    "checkpoints_renamed", "preserved_body_sha256",
]


@dataclass
class RelaunchAction:
    audit_row: dict[str, Any]
    batch: Path | None
    source_input: Path
    new_input: Path
    new_text: str
    source_output: Path | None
    archived_output: Path | None
    old_rows: list[dict[str, str]]
    new_rows: list[dict[str, str]]
    plan_row: dict[str, str]
    renamed_checkpoints: list[str] = field(default_factory=list)
    retired_inputs: list[str] = field(default_factory=list)


def _sha256_text(text: str) -> str:
    return hashlib.sha256(text.encode()).hexdigest()


def _sha256_file(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        while chunk := handle.read(1024 * 1024):
            digest.update(chunk)
    return digest.hexdigest()


def _attempt_is_unconfirmed(directory: Path, stem: str) -> bool:
    started = directory / f"{stem}.started"
    finished = directory / f"{stem}.finished"
    return started.is_file() and (
        not finished.is_file() or started.stat().st_mtime > finished.stat().st_mtime
    )


def _next_attempt(rows: list[dict[str, str]]) -> int:
    values: list[int] = []
    for row in rows:
        try:
            values.append(int(row.get("relaunch_attempt", "") or 0))
        except ValueError:
            pass
    return max(values, default=0) + 1


def _rewrite_routes(text: str, intent: str, order: int) -> tuple[str, str, str]:
    """Correct every optimizing route in a multi-stage input.

    Returns the rewritten text plus the before/after of the first optimizing
    route, for the plan and manifest record. Non-optimizing stages -- the
    ``Force`` label stage of a generated job -- are left exactly as they were.
    """
    pieces = _LINK1_SPLIT_RE.split(text)
    before = after = ""
    for index, piece in enumerate(pieces):
        if _LINK1_SPLIT_RE.fullmatch(piece):
            continue
        route = stage_route(piece)
        if not route or not route_optimizes(route):
            continue
        corrected = (
            corrected_saddle_route(route, order) if intent == "saddle"
            else corrected_minimum_route(route)
        )
        if corrected == route:
            continue
        if not before:
            before, after = route, corrected
        pieces[index] = _substitute_route(piece, route, corrected)
    return "".join(pieces), before, after


def _substitute_route(section: str, route: str, corrected: str) -> str:
    """Replace a stage's route block with a single corrected route line.

    The route may have been wrapped over several continuation lines; all of
    them are consumed so the corrected route is not appended to a fragment of
    the original.
    """
    lines = section.splitlines(keepends=True)
    start = next((i for i, line in enumerate(lines) if line.strip().startswith("#")), None)
    if start is None:
        return section
    end = start + 1
    while end < len(lines) and lines[end].strip():
        end += 1
    newline = "\n" if lines[start].endswith("\n") else ""
    return "".join(lines[:start]) + corrected + newline + "".join(lines[end:])


def _rename_checkpoints(text: str, suffix: str) -> tuple[str, list[str]]:
    """Point every %chk/%oldchk at a fresh name.

    The old checkpoints hold the wrong stationary point. Renaming keeps them on
    disk for inspection while guaranteeing the relaunch neither reads nor
    overwrites them, and it preserves each stage's lineage inside the job
    because every reference is renamed the same way.
    """
    renamed: list[str] = []

    def replace(match: re.Match[str]) -> str:
        value = Path(match.group(2))
        new_name = f"{value.stem}{suffix}{value.suffix or '.chk'}"
        renamed.append(f"{value.name}->{new_name}")
        return f"{match.group(1)}{value.with_name(new_name).as_posix()}"

    return _CHK_RE.sub(replace, text), renamed


def _body_digest(text: str) -> str:
    """Hash everything a route rewrite must not touch.

    Excludes route lines and ``%`` link directives; what remains is the title,
    the charge/multiplicity lines, the coordinates and any basis block. Compared
    before against after, this is a by-construction proof that the relaunch
    reuses the original guess geometry rather than anything derived from the
    discarded run.
    """
    body = [
        line.rstrip()
        for line in text.splitlines()
        if not line.lstrip().startswith(("#", "%"))
    ]
    return hashlib.sha256("\n".join(body).encode()).hexdigest()


def _write_csv(path: Path, fields: list[str], rows: list[dict[str, Any]]) -> None:
    temporary = path.with_name(path.name + ".tmp")
    with temporary.open("w", newline="", encoding="utf-8") as handle:
        writer = csv.DictWriter(handle, fieldnames=fields, extrasaction="ignore")
        writer.writeheader()
        writer.writerows(rows)
    temporary.replace(path)


def _planned_listing(batch: Path, actions: list[RelaunchAction]) -> list[str]:
    """The inputs.txt this batch will have: replacements in, retired names out.

    Order is preserved and the replacement takes the retired input's position,
    so the batch keeps its input ordering -- which is what slurm_plan.json's
    input fingerprint was computed over.
    """
    replacements = {
        action.source_input.name: action.new_input.name
        for action in actions if action.batch == batch
    }
    retired = {
        Path(name).name
        for action in actions if action.batch == batch
        for name in action.retired_inputs
    } - set(replacements)
    names: list[str] = []
    for raw in (batch / "inputs.txt").read_text(errors="replace").splitlines():
        name = raw.strip()
        if not name or name in retired:
            continue
        names.append(replacements.get(name, name))
    return names


def _preflight(campaign: Path, actions: list[RelaunchAction], plan: dict[str, Any]) -> list[str]:
    """Reject a plan that would leave the generated launchers in a bad state.

    The batch scripts are driven strictly by `inputs.txt` (`mapfile -t inputs <
    "$batch_file"`), never by globbing, and `RUN_POLICY=resume` decides per
    listed input whether a `<stem>.log` is complete. Everything checked here is
    a property that policy depends on, verified before a single file is
    touched, because a half-applied relaunch is far worse than a refused one.
    """
    problems: list[str] = []
    cpus = (plan.get("config") or {}).get("cpus_per_job")

    new_names = [action.new_input.name for action in actions]
    for name in sorted({n for n in new_names if new_names.count(n) > 1}):
        problems.append(f"two relaunches would write the same input name: {name}")

    for action in actions:
        # Only a spin manifest has one row per Link1 stage; a flat jobs.csv
        # keeps a single row for a job whose second stage is the Force label,
        # so comparing counts there would always disagree.
        is_ladder = any(row.get("intended_multiplicity") for row in action.new_rows)
        stages = 1 + sum(
            1 for line in action.new_text.splitlines()
            if line.strip().lower() == "--link1--"
        )
        if is_ladder and stages != len(action.new_rows):
            problems.append(
                f"{action.new_input.name}: {stages} Link1 stages but "
                f"{len(action.new_rows)} manifest rows; the ladder would be misdescribed"
            )
        if cpus:
            declared = re.findall(
                r"^\s*%nprocshared\s*=\s*(\d+)", action.new_text, re.IGNORECASE | re.MULTILINE
            )
            if any(int(value) != int(cpus) for value in declared):
                problems.append(
                    f"{action.new_input.name}: %nprocshared disagrees with the saved "
                    f"Slurm cpus_per_job={cpus}"
                )
        if action.batch is not None:
            # A relaunch must never collide with a still-live attempt's files.
            stem = action.new_input.stem
            for suffix in (".log", ".chk", ".rc", ".status", ".started", ".finished"):
                stray = action.batch / f"{stem}{suffix}"
                if stray.exists():
                    problems.append(f"{action.batch.name}: {stray.name} already exists")
            # The checkpoints the rebuilt job will write must not already be
            # there: Gaussian would silently overwrite them, and one of them
            # could belong to a job that is still running.
            for entry in action.renamed_checkpoints:
                _, _, produced = entry.partition("->")
                if produced and (action.batch / produced).exists():
                    problems.append(
                        f"{action.batch.name}: {produced} already exists and would be overwritten"
                    )

    for batch in sorted({a.batch for a in actions if a.batch is not None}):
        names = _planned_listing(batch, actions)
        if not names:
            problems.append(f"{batch.name}: inputs.txt would end up empty")
        duplicates = sorted({name for name in names if names.count(name) > 1})
        for name in duplicates:
            problems.append(f"{batch.name}: inputs.txt would list {name} twice")
        stems: dict[str, str] = {}
        for name in names:
            stem = Path(name).stem
            if stem in stems:
                problems.append(
                    f"{batch.name}: {name} and {stems[stem]} share output stem {stem}; "
                    "their .log files would collide"
                )
            stems[stem] = name
        expected = {action.new_input.name for action in actions if action.batch == batch}
        missing = expected - set(names)
        for name in sorted(missing):
            problems.append(f"{batch.name}: replacement {name} would not be listed")
    return problems


def _verify(campaign: Path, actions: list[RelaunchAction]) -> None:
    """Read back what was written; a mismatch here is a bug, not a user error."""
    for action in actions:
        if not action.new_input.is_file():
            raise RuntimeError(f"relaunch wrote no input at {action.new_input}")
        digest = _sha256_file(action.new_input)
        recorded = {row["input_sha256"] for row in action.new_rows}
        if recorded != {digest}:
            raise RuntimeError(
                f"{action.new_input.name}: manifest hash does not match the file on disk"
            )
        if action.source_output is not None and action.source_output.exists():
            raise RuntimeError(
                f"{action.source_output.name}: invalid output was not archived"
            )
    for batch in sorted({a.batch for a in actions if a.batch is not None}):
        listed = [
            name.strip()
            for name in (batch / "inputs.txt").read_text(errors="replace").splitlines()
            if name.strip()
        ]
        retired = {
            Path(name).name
            for action in actions if action.batch == batch
            for name in action.retired_inputs
        }
        for name in listed:
            if not (batch / name).exists():
                raise RuntimeError(f"{batch.name}/inputs.txt lists a missing input: {name}")
        active = {action.new_input.name for action in actions if action.batch == batch}
        for name in listed:
            if name in retired and name not in active:
                raise RuntimeError(
                    f"{batch.name}/inputs.txt still lists the retired input {name}"
                )
        for name in sorted(active):
            if name not in listed:
                raise RuntimeError(f"{batch.name}/inputs.txt is missing {name}")


def prepare_route_relaunch(
    campaign: Path,
    *,
    start: int = 1,
    end: int | None = None,
    assume_stopped: bool = False,
    dry_run: bool = False,
    saddle_order: int | None = None,
) -> dict[str, Any]:
    """Audit routes, then rebuild and activate corrected inputs in place."""
    campaign = campaign.resolve()
    manifest = find_manifest(campaign)
    audit = audit_campaign_routes(campaign)
    candidates = audit["relaunch"]
    assert isinstance(candidates, list)

    original_fields, all_rows = read_manifest(manifest)
    fields = list(dict.fromkeys(original_fields + RELAUNCH_COLUMNS))
    rows_by_input: dict[str, list[dict[str, str]]] = {}
    for row in all_rows:
        rows_by_input.setdefault((row.get("input") or "").strip(), []).append(row)

    slurm_plan_path = campaign / "slurm_plan.json"
    slurm_plan = (
        json.loads(slurm_plan_path.read_text(encoding="utf-8"))
        if slurm_plan_path.is_file() else {}
    )
    batch_root = campaign / "slurm_batches"
    numbers = [
        int(path.name[6:]) for path in batch_root.glob("batch_*")
        if path.is_dir() and path.name[6:].isdigit()
    ]
    final_batch = max(numbers, default=0)
    end = final_batch if end is None else end
    if final_batch and not 1 <= start <= end <= final_batch:
        raise ValueError(f"batch range must satisfy 1 <= start <= end <= {final_batch}")

    actions: list[RelaunchAction] = []
    skipped: list[dict[str, str]] = []
    overridden: list[dict[str, str]] = []

    def skip(row: dict[str, Any], reason: str) -> None:
        skipped.append({"input": row["input"], "batch": row["batch"], "reason": reason})

    for row in candidates:
        reference = row["input"]
        batch = batch_root / row["batch"] if row["batch"] else None
        if batch is not None:
            number = int(batch.name[6:])
            if not start <= number <= end:
                continue
        elif final_batch:
            skip(row, "input is not listed in any batch inputs.txt")
            continue
        if row["config_type"].removesuffix("_rattled") == "higher_order_saddle" \
                and saddle_order is None:
            skip(row, "higher_order_saddle needs an explicit --saddle-order")
            continue
        source_input = campaign / reference
        stem = source_input.stem
        directory = batch if batch is not None else source_input.parent
        if _attempt_is_unconfirmed(directory, stem):
            if not assume_stopped:
                skip(row, "activity_unconfirmed: pass --assume-stopped once squeue is clear")
                continue
            # --assume-stopped is a claim about the scheduler that this machine
            # cannot check -- QB4 cannot see QB3's queue. Overriding it
            # silently is how a still-running job gets its log archived out
            # from under it and a duplicate replacement submitted, so every
            # override is counted and reported rather than just applied.
            overridden.append({
                "input": reference,
                "batch": row["batch"],
                "detail": "unmatched .started marker; --assume-stopped overrode it",
            })

        group = rows_by_input.get(reference, [])
        if not group:
            skip(row, "input is absent from the campaign manifest")
            continue

        active_text = source_input.read_text(encoding="utf-8", errors="replace")
        origin = geometry_source(active_text)
        # A spin-ladder restart from prepare-spin-restarts carries no
        # coordinates: its first stage reads Geom=Checkpoint from a seed
        # checkpoint copied out of the interrupted run. Correcting such an
        # input in place would be wrong twice over -- there is no geometry in
        # it to correct, and that seed holds the collapsed minimum the plain
        # Opt produced. Go back to the root input, which still has the real
        # coordinates and the complete high-to-low multiplicity ladder, so the
        # rebuilt job reproduces the whole one-spin-flip-at-a-time pathway
        # rather than resuming a truncated one from a poisoned geometry.
        lineage_root = (group[0].get("restart_root_input") or "").strip() or reference
        if origin == "checkpoint":
            root_path = campaign / lineage_root
            if lineage_root == reference:
                skip(row, (
                    "first stage reads its geometry from a checkpoint but the manifest "
                    "records no restart_root_input, so the original coordinates cannot "
                    "be recovered; rebuild this ladder by hand from its seed record"
                ))
                continue
            if not root_path.is_file():
                skip(row, f"root ladder input is missing: {lineage_root}")
                continue
            root_text = root_path.read_text(encoding="utf-8", errors="replace")
            if geometry_source(root_text) != "input_coordinates":
                skip(row, f"root ladder input carries no coordinates either: {lineage_root}")
                continue
            rebuild_from, rebuild_text = root_path, root_text
            rebuild_rows = rows_by_input.get(lineage_root) or group
        elif origin == "input_coordinates":
            rebuild_from, rebuild_text, rebuild_rows = source_input, active_text, group
        else:
            skip(row, "cannot determine where this input's geometry comes from")
            continue

        # Retire the whole restart lineage, not just the currently active
        # attempt: every one of them descends from the same collapsed geometry.
        lineage_inputs = {reference, lineage_root} | {
            (item.get("input") or "").strip() for item in all_rows
            if (item.get("restart_root_input") or "").strip() == lineage_root
        }
        lineage_inputs.discard("")
        superseded = [
            item for item in all_rows
            if (item.get("input") or "").strip() in lineage_inputs
        ]
        attempt = _next_attempt(superseded)
        suffix = f"-routefix{attempt:02d}"
        new_stem = f"{Path(lineage_root).stem}__routefix{attempt:02d}"
        new_input = rebuild_from.with_name(new_stem + rebuild_from.suffix)

        text = rebuild_text
        intent = row["intent"]
        order = saddle_order or 1
        rewritten, before, after = _rewrite_routes(text, intent, order)
        if not before:
            skip(row, (
                "route already requests the right search, so a rewrite would change "
                f"nothing ({row['findings']}); this needs a better guess geometry, "
                "not a relaunch"
            ))
            continue
        rewritten, renamed = _rename_checkpoints(rewritten, suffix)
        if _body_digest(rewritten) != _body_digest(text):
            raise RuntimeError(
                f"{reference}: rewriting the route changed the molecular specification; "
                "refusing to relaunch from a geometry this tool altered"
            )

        source_output = campaign / row["output"] if row["output"] else None
        archived_output = None
        if source_output is not None and source_output.is_file():
            archived_output = source_output.with_name(
                f"{source_output.stem}__before-routefix{attempt:02d}{source_output.suffix}"
            )
        targets = [new_input] + ([archived_output] if archived_output else [])
        if batch is not None:
            targets.append(batch / new_input.name)
        existing = [target for target in targets if target.exists() or target.is_symlink()]
        if existing:
            skip(row, f"relaunch target already exists: {existing[0].name}")
            continue

        # Built from the *root* ladder's rows, so the rebuilt manifest carries
        # every multiplicity of the pathway again rather than the truncated
        # tail a restart was left with.
        new_rows: list[dict[str, str]] = []
        for old_row in rebuild_rows:
            new_row = {column: old_row.get(column, "") for column in fields}
            new_row.update({
                "input": str(Path(lineage_root).with_name(new_input.name).as_posix()),
                "output": f"{new_stem}.log",
                # Replaced with the digest of the file as written; see below.
                "input_sha256": _sha256_text(rewritten),
                "submission_active": "true",
                "relaunch_attempt": str(attempt),
                "relaunch_reason": row["findings"],
                "relaunch_root_input": lineage_root,
                "relaunch_of_job_id": old_row.get("job_id", ""),
                "relaunch_source_output": (
                    str(archived_output.relative_to(campaign)) if archived_output else ""
                ),
                "relaunch_route_before": before,
                "relaunch_route_after": after,
                "route_invalidated": "",
                "superseded_by_job_id": "",
            })
            if old_row.get("job_id"):
                new_row["job_id"] = f"{old_row['job_id']}-rf{attempt:02d}"
            if "first_route" in new_row and new_row["first_route"]:
                new_row["first_route"] = after
            new_rows.append(new_row)

        plan_row = {
            "attempt": str(attempt),
            "batch": batch.name if batch else "",
            "original_input": reference,
            "new_input": str(Path(lineage_root).with_name(new_input.name).as_posix()),
            "config_type": row["config_type"],
            "findings": row["findings"],
            "previous_state": row["state"],
            "geometry_source": origin,
            "rebuilt_from": lineage_root,
            "retired_inputs": ";".join(sorted(lineage_inputs)),
            "ladder_stages": str(len(new_rows)),
            "archived_output": (
                str(archived_output.relative_to(campaign)) if archived_output else ""
            ),
            "new_output": f"{new_stem}.log",
            "route_before": before,
            "route_after": after,
            "checkpoints_renamed": ";".join(renamed),
            "preserved_body_sha256": _body_digest(rewritten),
        }
        actions.append(RelaunchAction(
            audit_row=row, batch=batch, source_input=source_input, new_input=new_input,
            new_text=rewritten, source_output=source_output, archived_output=archived_output,
            old_rows=superseded, new_rows=new_rows, plan_row=plan_row,
            renamed_checkpoints=renamed, retired_inputs=sorted(lineage_inputs),
        ))

    result: dict[str, Any] = {
        "campaign": str(campaign),
        "audit_summary": audit["summary"],
        "input_count": len(actions),
        "job_row_count": sum(len(action.new_rows) for action in actions),
        "plan": [action.plan_row for action in actions],
        "skipped": skipped,
        "overridden_active_attempts": overridden,
        "dry_run": dry_run,
        "report": str(audit["destination"]),
    }
    problems = _preflight(campaign, actions, slurm_plan)
    result["launcher_problems"] = problems
    if dry_run:
        return result
    if not actions:
        raise RuntimeError(
            "no jobs need a route relaunch"
            + (f" ({len(skipped)} skipped; see the audit report)" if skipped else "")
        )
    if problems:
        raise RuntimeError(
            "refusing to relaunch: the result would leave the generated launchers "
            "inconsistent, and a half-applied relaunch is worse than none:\n  - "
            + "\n  - ".join(problems)
        )

    stamp = datetime.now(timezone.utc).strftime("%Y%m%dT%H%M%S%fZ")
    backups = campaign / "route_fix_backups"
    backups.mkdir(exist_ok=True)
    shutil.copy2(manifest, backups / f"{manifest.stem}.{stamp}.csv")
    touched = sorted({action.batch for action in actions if action.batch is not None})
    for batch in touched:
        shutil.copy2(batch / "inputs.txt", backups / f"{batch.name}.inputs.{stamp}.txt")

    for action in actions:
        action.new_input.parent.mkdir(parents=True, exist_ok=True)
        action.new_input.write_text(action.new_text, encoding="utf-8")
        written = _sha256_file(action.new_input)
        for row in action.new_rows:
            row["input_sha256"] = written
        if action.source_output is not None and action.archived_output is not None:
            action.source_output.rename(action.archived_output)
            for suffix in _MARKER_SUFFIXES:
                marker = action.source_output.with_suffix(suffix)
                if marker.exists():
                    marker.rename(action.archived_output.with_suffix(suffix))
        if action.batch is not None:
            link = action.batch / action.new_input.name
            try:
                link.symlink_to(os.path.relpath(action.new_input, action.batch))
            except OSError:
                # Unprivileged symlink creation is disabled by default on
                # Windows; a copy behaves identically for the batch worker.
                shutil.copy2(action.new_input, link)

    for batch in touched:
        names = _planned_listing(batch, actions)
        (batch / "inputs.txt").write_text("\n".join(names) + "\n", encoding="utf-8")

    for action in actions:
        replacement_by_job = {
            row.get("relaunch_of_job_id", ""): row.get("job_id", "")
            for row in action.new_rows
        }
        active_input = action.audit_row["input"]
        for old_row in action.old_rows:
            old_row["submission_active"] = "false"
            old_row["route_invalidated"] = action.audit_row["findings"]
            old_row["superseded_by_job_id"] = replacement_by_job.get(
                old_row.get("job_id", ""), ""
            )
            # Only the attempt whose log this run archived gets a new output
            # name. Earlier attempts in the lineage were already archived by
            # prepare-spin-restarts under their own names and still point at
            # the logs they actually produced.
            if action.archived_output is not None and (
                    old_row.get("input") or "").strip() == active_input:
                old_row["output"] = action.archived_output.name
        all_rows.extend(action.new_rows)
    _write_csv(manifest, fields, all_rows)

    plan_path = campaign / "route_fix_plan.csv"
    existing_plan: list[dict[str, str]] = []
    if plan_path.is_file():
        _, existing_plan = read_manifest(plan_path)
    _write_csv(plan_path, PLAN_COLUMNS,
               existing_plan + [action.plan_row for action in actions])
    _write_csv(campaign / "skipped_route_fixes.csv",
               ["input", "batch", "reason"], skipped)
    if overridden:
        _write_csv(campaign / "route_fix_overrides.csv",
                   ["input", "batch", "detail"], overridden)
    # Read back what is now on disk. The preflight checked the plan; this
    # checks the result, so the campaign is never left in a state the
    # launchers would run incorrectly without anyone being told.
    _verify(campaign, actions)

    for name in ("spin_campaign.json", "campaign_manifest.json"):
        metadata_path = campaign / name
        if not metadata_path.is_file():
            continue
        metadata = json.loads(metadata_path.read_text(encoding="utf-8"))
        if "manifest_sha256" in metadata:
            metadata["manifest_sha256"] = _sha256_file(manifest)
        if "jobs_csv_sha256" in metadata:
            metadata["jobs_csv_sha256"] = _sha256_file(manifest)
        history = metadata.setdefault("route_fix_history", [])
        history.append({
            "created_utc": datetime.now(timezone.utc).isoformat(),
            "batch_range": [start, end],
            "input_count": len(actions),
            "job_row_count": sum(len(action.new_rows) for action in actions),
        })
        metadata_path.write_text(
            json.dumps(metadata, indent=2, sort_keys=True) + "\n", encoding="utf-8"
        )

    result["backup"] = str(backups)
    return result
